/**
 * Node 7/7 — generate_and_save_report (Code)
 *
 * Formats git_metadata + llm_analysis into a comprehensive Markdown report and
 * writes it atomically to:
 *
 *   .harness/<repo_name>/report/analysis.md
 *
 * Also writes the raw structured data as JSON to:
 *
 *   .harness/<repo_name>/.harness/analysis_<timestamp>.json
 *
 * Atomic write pattern: content is written to a tmp file in the same directory,
 * then renameSync() is called so readers never see a partial file.
 *
 * After writing, the conditional edge in graph.ts routes back to clone_target_repo
 * if the queue is non-empty, or to END if the queue is exhausted.
 *
 * State reads:  current_repo, git_metadata, llm_analysis, extracted_files, error_logs
 * State writes: last_step
 */

import { mkdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import * as path from "node:path";

import { banner, getLogger } from "../loggingSetup.js";
import type { WorkflowState } from "../state.js";

const log = getLogger("node-7");

export async function generateAndSaveReport(state: WorkflowState): Promise<Partial<WorkflowState>> {
  banner("Step 7/7 -- generate_and_save_report");

  const currentRepo = state.current_repo || {};
  const gitMetadata = state.git_metadata || {};
  const llmAnalysis = state.llm_analysis || {};
  const extractedFiles = state.extracted_files || {};
  const errorLogs = state.error_logs || [];

  const owner = currentRepo.owner || "unknown";
  const name = currentRepo.name || "unknown";
  const cloneDir = currentRepo.clone_dir || path.join(".harness", name);
  const repoSlug = `${owner}/${name}`;
  const runTs = utcStamp();

  log.info("Generating report for %s (run=%s)", repoSlug, runTs);
  console.log(`[node-7] Generating report for ${repoSlug} (run=${runTs})`);

  const reportDir = path.join(cloneDir, "report");
  const outputDir = path.join(cloneDir, ".harness");
  mkdirSync(reportDir, { recursive: true });
  mkdirSync(outputDir, { recursive: true });

  // ── Build Markdown report ──────────────────────────────────────────────
  const manifestKeys = Object.keys(extractedFiles)
    .filter((k) => !k.startsWith("__"))
    .sort();
  const pmList = strList(llmAnalysis.package_managers) || "_none detected_";
  const tfList = strList(llmAnalysis.testing_frameworks) || "_none detected_";

  const mdLines: string[] = [
    `# Repository Analysis -- ${repoSlug}`,
    "",
    `**Run timestamp:** ${runTs}  `,
    `**Source:** https://github.com/${repoSlug}  `,
    `**Harness:** Agent + Helpers (cross-repo-deep-analysis-engine)  `,
    "",
    "---",
    "",
    "## Git Metadata",
    "",
    "| Metric | Count |",
    "|---|---|",
    `| Branches | ${valueOr(gitMetadata.branches)} |`,
    `| Tags | ${valueOr(gitMetadata.tags)} |`,
    `| Releases | ${valueOr(gitMetadata.releases)} |`,
    "",
    "## Stack Analysis",
    "",
    `**Primary language:** ${str(llmAnalysis.primary_language) || "_unknown_"}  `,
    `**Package managers:** ${pmList}  `,
    "",
    "### Installation",
    "",
    str(llmAnalysis.installation_steps) || "_No data._",
    "",
    "### Build Process",
    "",
    str(llmAnalysis.build_process) || "_No data._",
    "",
    "### Testing Frameworks",
    "",
    tfList,
    "",
    "### CI/CD Notes",
    "",
    str(llmAnalysis.ci_cd_notes) || "_No workflows found._",
    "",
    "## Random File Context",
    "",
    `**File sampled:** \`${str(llmAnalysis.random_file_path) || "none"}\``,
    "",
    str(llmAnalysis.random_file_summary) || "_No random file was analysed for this repository._",
    "",
  ];

  if (errorLogs.length) {
    mdLines.push("## Errors / Warnings (this run)", "");
    for (const err of errorLogs) {
      mdLines.push(`- ${err}`);
    }
    mdLines.push("");
  }

  mdLines.push("## Extracted Files Index", "");
  for (const k of manifestKeys) {
    mdLines.push(`- \`${k}\``);
  }
  if (manifestKeys.length === 0) {
    mdLines.push("_No manifest or workflow files extracted._");
  }
  mdLines.push("");
  mdLines.push("---", `_Generated by cross-repo-deep-analysis-engine -- ${runTs}_`, "");

  const reportMd = mdLines.join("\n");

  // Atomic write: tmp file + renameSync.
  const reportPath = path.join(reportDir, "analysis.md");
  atomicWrite(reportPath, reportMd);
  log.info("Report written: %s", reportPath);
  console.log(`[node-7] Report written: ${reportPath}`);

  // ── Write raw structured JSON ──────────────────────────────────────────
  const outputPayload = {
    run_timestamp: runTs,
    repo: repoSlug,
    git_metadata: gitMetadata,
    llm_analysis: llmAnalysis,
    extracted_file_paths: manifestKeys,
    error_logs: errorLogs,
  };
  const outputPath = path.join(outputDir, `analysis_${runTs}.json`);
  atomicWrite(outputPath, JSON.stringify(outputPayload, null, 2));
  log.info("Raw output written: %s", outputPath);
  console.log(`[node-7] Raw output written: ${outputPath}`);

  return { last_step: "generate_and_save_report" };
}

/** UTC timestamp in the form YYYYMMDDTHHMMSSZ. */
function utcStamp(): string {
  return new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d+Z$/, "Z");
}

function str(v: unknown): string {
  return typeof v === "string" ? v : v == null ? "" : String(v);
}

function strList(v: unknown): string {
  return Array.isArray(v) ? v.map((x) => String(x)).join(", ") : "";
}

function valueOr(v: unknown): string {
  return v === undefined || v === null ? "n/a" : String(v);
}

/** Write *content* to *target* atomically via a temp file + renameSync(). */
function atomicWrite(target: string, content: string): void {
  mkdirSync(path.dirname(target), { recursive: true });
  const tmp = path.join(
    path.dirname(target),
    `.tmp_${process.pid}_${Math.floor(Math.random() * 1e9)}${path.extname(target)}`,
  );
  try {
    writeFileSync(tmp, content, "utf-8");
    renameSync(tmp, target);
  } catch (exc) {
    try {
      rmSync(tmp, { force: true });
    } catch {
      /* ignore cleanup failure */
    }
    throw exc;
  }
}
